spring:
  application:
    name: vp-processor-worker
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:60000}

aws:
  region: ${AWS_REGION:sa-east-1}
  s3:
    bucket:
      video: ${S3_VIDEO_BUCKET:hack-vp-videos}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    auto-offset: ${AUTO_OFFSET_RESET_CONFIG:earliest}
    topic: ${VIDEO_PROCESSOR_TOPIC:video-processor-topic}
    group-id: ${VIDEO_PROCESSOR_GROUP_ID:video-processor}
  producer:
    topic:
      notification: ${VIDEO_NOTIFICATION_TOPIC:VideoFailed.v1}
      upload-status: ${VIDEO_UPLOAD_TOPIC:VideoUpload.v1}

ffmpeg:
  path: ${FFMPEG_PATH:}

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

probe:
  path: /actuator/health
  port: http
  initialDelaySecondsLiveness: 120
  initialDelaySecondsReadness: 120